services:
  # Servicio OCR API (wrapper FastAPI) que orquesta MinerU por CLI
  ocr-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr-api
    restart: unless-stopped
    ports:
      - "${MINERU_PORT:-8001}:8000"  # host:container
    environment:
      - GPU_ENABLED=${GPU_ENABLED:-true}
      - GPU_DEVICE=${GPU_DEVICE:-cuda}
      - GPU_BACKEND=${GPU_BACKEND:-pipeline}
      - MODEL_PATH=${MODEL_PATH:-/models}
      - CACHE_DIR=${CACHE_DIR:-/cache}
      - METRICS_ENABLED=${METRICS_ENABLED:-true}
      - MINERU_VRAM_PER_WORKER_MB=${MINERU_VRAM_PER_WORKER_MB:-768}
      - OMP_NUM_THREADS=${OMP_NUM_THREADS:-1}
      - MKL_NUM_THREADS=${MKL_NUM_THREADS:-1}
      - OPENBLAS_NUM_THREADS=${OPENBLAS_NUM_THREADS:-1}
      - NUMEXPR_NUM_THREADS=${NUMEXPR_NUM_THREADS:-1}
    volumes:
      - ./models:/models
      - ./cache:/cache
      - ./data:/data
    gpus: all
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  # UI opcional de Gradio para inspección manual (no impacta al backend)
  mineru-gradio:
    image: lmsysorg/sglang:v0.4.9.post6-cu126
    container_name: mineru-gradio
    restart: unless-stopped
    profiles: ["gradio"]
    ports:
      - "7860:7860"
    environment:
      MINERU_MODEL_SOURCE: local
    entrypoint: mineru-gradio
    command:
      --server-name 0.0.0.0
      --server-port 7860
      --enable-sglang-engine true
    gpus: all